#All the PVS are given 1GB, but this is kustomized using the overlays so that prod has more space vs dev
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  selector:
    matchLabels:
      app: zeir-app
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pv-claim
  labels:
    app: zeir-app
spec:
  selector:
    matchLabels:
      app: couchdb
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-lucene-pv-claim
  labels:
    app: zeir-app
spec:
  selector:
    matchLabels:
      app: couchdb-lucene-app
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmrs-pv-claim
  labels:
    app: zeir-app
spec:
  selector:
    matchLabels:
      app: openmrs-app
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: zeir-app
spec:
  selector:
    matchLabels:
      app: zeir-redis-app
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: zeir-app
spec:
  selector:
    matchLabels:
      app: zeir-postgres-app
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
