---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-5-6-pv-claim
spec:
  selector:
    matchLabels:
      app: zeir-app
      environment: development
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
