apiVersion: v1
kind: Service
metadata:
  name: couchdb-1-6-1-svc
spec:
  ports:
  - port: 5984
  selector:
    app: couchdb-1-6-1-app
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-1-6-1-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: couchdb-1-6-1-app
spec:
  serviceName: "couchdb-1-6-1-svc"
  selector:
    matchLabels:
      app: couchdb-1-6-1-app
  template:
    metadata:
      labels:
        app: couchdb-1-6-1-app
    spec:
      containers:
      - image: couchdb:1.6.1
        name: couchdb-1-6-1-container
        env:
        - name: COUCHDB_USER
          value: couch
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-1-6-1-passwords
              key: couchdb-password
        ports:
        - containerPort: 5954
          name: couch-port
        volumeMounts:
        - name: couchdb-1-6-1-storage
          mountPath: /var/local/var/lib/couchdb
      volumes:
      - name: couchdb-1-6-1-storage
        persistentVolumeClaim:
          claimName: couchdb-1-6-1-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-lucene-svc
spec:
  ports:
  - port: 5985
  selector:
    app: couchdb-lucene-app
  type:
    LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-lucene-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcerv-openmrs-app
spec:
  selector:
    matchLabels:
      app: smartcerv-openmrs-app
  template:
    metadata:
      labels:
        app: smartcerv-openmrs-app
    spec:
      containers:
      - image: openmrs/openmrs-reference-application-distro
        name: smartcerv-openmrs-container
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: smartcerv-mysql-service
        - name: DB_DATABASE
          value: smartcerv
        - name: DB_USERNAME
          value: smartcerv
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smartcerv-mysql-passwords
              key: mysql-root-password
        - name: DB_CREATE_TABLES
          value: 'false'
        - name: DB_AUTO_UPDATE
          value: 'false'
        - name: MODULE_WEB_ADMIN
          value: 'true'
        ports:
        - containerPort: 8080
          name: smartcerv
        volumeMounts:
        - name: openmrs-persistent-storage
          mountPath: /usr/local/tomcat/.OpenMRS
      volumes:
      - name: openmrs-persistent-storage
        persistentVolumeClaim:
          claimName: smartcerv-openmrs-pv-claim

