kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisoner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1-zeir
  labels:
    type: local
    app: couchdb-lucene-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-1-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-12-zeir
  labels:
    type: local
    app: openmrs-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-12-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10-zeir
  labels:
    type: local
    app: openmrs-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-10-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2-zeir
  labels:
    type: local
    app: openmrs-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-2-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3-zeir
  labels:
    type: local
    app: couchdb-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-3-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-4-zeir
  labels:
    type: local
    app: zeir-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-4-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5-zeir
  labels:
    type: local
    app: zeir-redis-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-5-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-6-zeir
  labels:
    type: local
    app: zeir-postgres-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-6-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-7-zeir
  labels:
    type: local
    app: opensrp-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-7-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-8-zeir
  labels:
    type: local
    app: opensrp-build-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt/k8s/pv-8-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-9-zeir
  labels:
    type: local
    app: opensrp-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-9-zeir"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nacmis-1
  labels:
    type: local
    app: nacmis-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-nacmis-1"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nacmis-2
  labels:
    type: local
    app: nacmis-app
spec:
  storageClassName: local-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/k8s/pv-nacmis-2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - proxy
