apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-5-6-pv
  labels:
    type: local
    app: mysql-5-6-app
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-5-7-pv
  labels:
    type: local
    app: mysql-5-7-app
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smartcerv-openmrs-pv
  labels:
    type: local
    app: smartcerv-openmrs-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv 
  labels:
    type: local
    app: zookeeper-app
spec:
  storageClassName: manual
  capacity: 
    storage: 12Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 2Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
